### ISSUE TITLE
Comments...

### ISSUE THREAD

**Issue by ejflick** [dimitryraymond/TetrisBox#1]
Where yo comments at?

**Comment by dimitryraymond** [comment]
lol

**Comment by dimitryraymond** [comment]
Coming next patch, since other ppl now see

**Comment by ejflick** [comment]
*people

**Comment by dimitryraymond** [comment]
Still no comments lol

**Comment by dimitryraymond** [comment]
Going to close this issue as being a feature request

**Comment by dimitryraymond** [comment]
Going to close this issue as being a feature request

**Comment by ejflick** [comment]
Lame

**Comment by dimitryraymond** [comment]
Maybe when I come back to this, but now I must move on to bigger things.

**Comment by ejflick** [comment]
Like coming to visit me next month. I'll comment on those bigger things
when you finally put them on GitHub...and expect that to be TONIGHT.
On Jul 1, 2016 9:30 PM, "Dimitry Raymond" <notifications@github.com> wrote:

Maybe when I come back to this, but now I must move on to bigger things.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dimitryraymond/TetrisBox/issues/1#issuecomment-230082921>,
or mute the thread
<https://github.com/notifications/unsubscribe/ADSK-COMCWNbUsZNT1sWbH_3XrGSMYZ4ks5qRelGgaJpZM4DZGHj>
.

**Comment by dimitryraymond** [comment]
lol
